### PR TITLE
Add Queue module

### PR DESCRIPTION
**Pull request by thecodewarrior**
Added a queue module that operates as a FIFO buffer.

I also updated the stack module's texture to show the IO:

Left is queue, right is stack.

If this gets accepted I will create an issue for the translation of the new entries. The things that need translating are: Queue module item, queue module doc entry, last paragraph of stack module doc entry, queue module list entry in items index.md

### CODE REVIEW

**Comment by Vexatos** [comment]
I honestly don't like the module textures. The item textures are fine.

**Comment by thecodewarrior** [comment]
I'm not great at this whole "art" thing, so I'd be happy to change them if you want me to.

**Comment by thecodewarrior** [comment]
Any suggestions on what they should look like?

**Comment by fnuecke** [comment]
Oh my god, so sorry. For some reason I didn't get notification eMails so I didn't see your PRs until now D:
So I apparently implemented what you already had, what a waste. I feel dumb now. At least people can blame me now for lack of imaginative texturework.

**Pull request closed without merging**
