### PR TITLE
Lightweight Modules

### PR DESCRIPTION
**Pull request by ghost**
Lightweight Modules (or the "Custom Module" as shown in the UI) are server-side pluggable modules that a server operator, or the local user on Singleplayer, can define.

They use a cut-down version of the Module API, designed to avoid a dependency on Minecraft - this ensures that Lightweight Modules are less version-dependent.

They are currently crafted with an apple, for lack of any better ideas. (This crafting recipe will not be defined if no Custom Modules are enabled. Not sure if this is a good or bad thing...)

Currently the default configuration points at a test module that exists to ensure the system works.
Said test module could use a lot of bandwidth, as it's mostly a test of the display.
However, a server operator can change this to nothing at all, or their own modules.

Lightweight Modules have a (full, with no margin - maybe add a margin _without_ lowering effective resolution?), but 64x64 pixels is probably needed to fit various bits of text that someone may need/want to display) 64x64 pixel screen with 16 colours, that is delta-encoded to try and preserve bandwidth. This is how users see what the lightweight module is doing.
This delta encoding required that the usual packet ordering be reversed for it's packets, and the usual netcode "delete earlier packets" system not used unfortunately, but it should be worth it because of the deltas, assuming servers don't get too enthusiastic with their modules.

Note that this PR is only for the 1.8.9 branch, and will need backporting if it's going to work anywhere else. Hopefully that won't be too problematic.

Known problems:
1. Custom Modules don't get manual entries, but there is a general one for the Custom Module item itself.
2. How to define them, and how to write up a good flavour-texty reason for them? Right now I've made an attempt at some in-world reason on how they work yet are so ambiguous, but it's not exactly good...
3. Custom Modules might be a confusing name, IDK.
4. Is there a better way of dealing with the fact that the deltas need to be applied in order...?
5. Currently the names of the modules are entirely based on class name.
6. The way tooltips and such are done might be wrong, incorrect, or just plain messy. (At least the pre-made strings are internationalized, I guess...)
7. There is no internationalization on the on-module "No Function" and "No Lw Module ; See Log" error displays.

### CODE REVIEW

**Comment by Vexatos** [comment]
> Files changed (24)

I approve of this lightweightness. :suspect: 

Frankly, it looks pretty quite useless to me. Apart from unnecessarily breaking the API, that is. is there any reason to have this? It... looks like a redundantly complicated and slow display module. I get the intention of being able to do server-side modules but it REALLY does not even remotely look worth all this mess and ugly code. And definitely not the redundant API breakage (why?). You know, one could just add a serial interface on the server side instead of all this for any random block and achieve the same thing.

**Comment by ghost** [comment]
I'm a tad wondering how it breaks the API - as far as I know I haven't removed anything from it or done anything that would break the API... Is the API-breaking because of ModuleBase?
The "redundantly complicated display module" is actually what the "host" module was based on - lightweight modules need a display of some form, and we can't easily go moving textures to the client.
As it is, the lightweightness is on the module writer's side, not the implementation (because, you know, server-side only, etc.)
As for the mess and ugly code, I'd like some notes on where.
(Also, a serial interface on the serverside for a random block, to me, sounds more messy.)

**Comment by Vexatos** [comment]
I think it's completely useless. TIS-3D is all about not having modules that do too little and this, in my opinion, is _way_ too specific-use-case to be worth this implementation. Perhaps make it an addon (it would be very much possible as an addon with WAY less code and without modifying the API this much), but this shouldn't go into TIS-3D itself.

**Comment by ghost** [comment]
Ah, I see. In which case, closing PR w/no merge.

**Pull request closed without merging**
