### PR TITLE
Modulo operator

### PR DESCRIPTION
**Pull request by TimovVeen**
Simply adds a modulo (MOD) operation to the execution module. I think it fits alongside the MUL and DIV operations for technically being possible with some workaround, so this would give some convenience to the modulo enjoyers out there.

### CODE REVIEW

**Comment by fnuecke** [comment]
Sure, makes sense - and looks good to me!  One ask though: would you mind also adding the documentation to at least the English [in-game manual page of the execution module](https://github.com/MightyPirates/TIS-3D/blob/1.20.1/common/src/main/resources/assets/tis3d/doc/en_us/item/execution_module.md), so that people will know it exists?  Thanks.

**Comment by TimovVeen** [comment]
Of course, forgot about the manual. I'll add it in a minute

**Comment by TimovVeen** [comment]
Added it :)

**Comment by fnuecke** [comment]
Thanks again!

**Pull request merged**
